# 视觉小说应用配置文件 (config.toml)

[app]
name = "心之旅程"
version = "1.0.0"
author = "视觉小说工作室"
description = "一个引人入胜的视觉小说游戏"

[window]
title = "心之旅程"
width = 1280
height = 720
resizable = true
fullscreen = false
background_color = "#000000"
icon = "assets/icons/app_icon.png"

[game]
default_save_directory = "saves"
auto_save_enabled = true
auto_save_interval = 300         # 自动保存间隔（秒）
max_save_slots = 100
text_speed = 40                  # 文字显示速度（字符/秒）

[audio]
bgm_volume = 0.7
sfx_volume = 0.8
voice_volume = 1.0
mute_on_unfocus = true

[ui]
font_main = "assets/fonts/main.ttf"
font_dialog = "assets/fonts/dialog.ttf"
text_color = "#FFFFFF"
name_text_color = "#FFD700"
dialog_opacity = 0.8
dialog_position = "bottom"              # bottom, top, center
skip_unread = false
auto_mode_delay = 2.0                   # 自动模式下对话之间的延迟（秒）

[paths]
backgrounds = "assets/backgrounds"
characters = "assets/characters"
music = "assets/audio/music"
sounds = "assets/audio/sfx"
voices = "assets/audio/voices"
scripts = "scripts"

[characters]
# 角色定义
[characters.protagonist]
name = "主角"
color = "#3498DB"

[characters.heroine]
name = "女主角"
color = "#E91E63"

[characters.friend]
name = "朋友"
color = "#2ECC71"

[characters.antagonist]
name = "对手"
color = "#E74C3C"

[effects]
transitions_enabled = true
particles_enabled = true
animations_enabled = true
default_transition = "fade" # fade, dissolve, slide
transition_duration = 0.5   # 过渡效果持续时间（秒）

[development]
debug_mode = false
log_level = "info"     # debug, info, warning, error
enable_console = false

[localization]
default_language = "zh-CN"
available_languages = ["zh-CN", "en-US", "ja-JP"]

[achievements]
enabled = true
show_notifications = true

[preferences]
# 用户首选项默认值
skip_after_choices = true
continue_skipping_after_choices = false
hide_ui_when_idle = true
idle_timeout = 3.0                      # UI隐藏前的空闲时间（秒）
